kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: my-role-binding
  namespace:"default"
subjects:
- kind: ServiceAccount
  name: kubernetes
roleRef:
  kind: Role
  name: my-role
  apiGroup: rbac.authorization.k8s.io
